### ISSUE TITLE
Modify spacing

### ISSUE THREAD

**Issue by icaoberg** [CBDatCMU/cbd-directory#3]
Descriptive info should be a little closer to people's photos.

**Comment by uhq1** [comment]
done by setting margin to 0 0 0 0 for each image.
Before:
![screen shot 2018-06-06 at 13 55 14](https://user-images.githubusercontent.com/22680399/41056179-5029cbee-6991-11e8-85ec-96751f537934.png)

After:
![screen shot 2018-06-06 at 13 54 32](https://user-images.githubusercontent.com/22680399/41056186-54278204-6991-11e8-95de-a181f5a0313a.png)

**Comment by uhq1** [comment]
https://github.com/icaoberg/cbd-directory/pull/9
