### ISSUE TITLE
Change font size

### ISSUE THREAD

**Issue by icaoberg** [CBDatCMU/cbd-directory#4]
Font could be bigger for professors' offices.

**Comment by uhq1** [comment]
increased font size for faculty room numbers from 10px to 12px. Increased undergraduate names and year from 10px respectively to 16px and 12px respectively.

Faculty before:
![screen shot 2018-06-06 at 14 01 23](https://user-images.githubusercontent.com/22680399/41056454-3c9808d8-6992-11e8-8b01-beef8936889a.png)

Faculty after:
![screen shot 2018-06-06 at 14 00 59](https://user-images.githubusercontent.com/22680399/41056465-41fcbd5a-6992-11e8-976f-303280d9c9ce.png)

**Comment by uhq1** [comment]
Undergrad before:
![screen shot 2018-06-06 at 14 04 01](https://user-images.githubusercontent.com/22680399/41056539-7de59b0c-6992-11e8-8b11-89b9ef7ed787.png)

Undergrad after:
![screen shot 2018-06-06 at 14 03 13](https://user-images.githubusercontent.com/22680399/41056549-83dc968c-6992-11e8-8522-454356b06de3.png)

**Comment by uhq1** [comment]
https://github.com/icaoberg/cbd-directory/pull/10
