### ISSUE TITLE
Change headers

### ISSUE THREAD

**Issue by icaoberg** [CBDatCMU/cbd-directory#5]
If something is multiple pages (e.g., voting faculty), would be better to see "Voting Faculty (1/2)" that kind of thing.

**Comment by uhq1** [comment]
Changed headers for voting faculty and mscb students.

Voting Faculty (1/2)
![screen shot 2018-06-06 at 14 09 18](https://user-images.githubusercontent.com/22680399/41056805-5586d6b6-6993-11e8-8fcc-0c40e12ecdbb.png)

Voting Faculty (2/2)
![screen shot 2018-06-06 at 14 09 24](https://user-images.githubusercontent.com/22680399/41056821-5c946892-6993-11e8-8ac8-5719913a49b8.png)

MSCB Students (1/2)
![screen shot 2018-06-06 at 14 09 33](https://user-images.githubusercontent.com/22680399/41056833-638c05f6-6993-11e8-8440-08e4184f7054.png)

MSCB Students (2/2)
![screen shot 2018-06-06 at 14 09 41](https://user-images.githubusercontent.com/22680399/41056845-6d80b598-6993-11e8-9ed2-304342e828ca.png)

**Comment by uhq1** [comment]
https://github.com/icaoberg/cbd-directory/pull/11
